=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for LeanixApi::BookmarkSharesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BookmarkSharesApi' do
  before do
    # run before each test
    @api_instance = LeanixApi::BookmarkSharesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BookmarkSharesApi' do
    it 'should create an instance of BookmarkSharesApi' do
      expect(@api_instance).to be_instance_of(LeanixApi::BookmarkSharesApi)
    end
  end

  # unit tests for create_bookmark_share
  # createBookmarkShares
  # Saves a bookmark share in the database
  # @param [Hash] opts the optional parameters
  # @option opts [BookmarkShareInputData] :bookmark_share Field SharedByUserId, if set, needs to be same as the calling user&#39;s id.
  # @return [BookmarkSharesResponse]
  describe 'create_bookmark_share test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_bookmark_share
  # deleteBookmarkShares
  # Deletes a bookmark share by the calling user.
  # @param bookmark_id Specifies the bookmark id
  # @param shared_with_user_id Specifies the sharedWith userId
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_bookmark_share test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_bookmark_shares
  # getBookmarkShares
  # Retrieves all stored bookmark shared by the calling user.
  # @param bookmark_id Specifies the bookmark id
  # @param [Hash] opts the optional parameters
  # @return [BookmarkSharesResponse]
  describe 'get_bookmark_shares test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
