=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for LeanixApi::FeaturesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FeaturesApi' do
  before do
    # run before each test
    @api_instance = LeanixApi::FeaturesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FeaturesApi' do
    it 'should create an instance of FeaturesApi' do
      expect(@api_instance).to be_instance_of(LeanixApi::FeaturesApi)
    end
  end

  # unit tests for get_feature
  # getFeature
  # Retrieves a feature for a workspace
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [FeatureResponse]
  describe 'get_feature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_features
  # getFeatures
  # Retrieves features for current workspace
  # @param [Hash] opts the optional parameters
  # @return [FeatureListResponse]
  describe 'get_features test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upsert_feature
  # updateFeature
  # Change properties of a feature for a workspace (ADMIN role only)
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :enabled 
  # @return [FeatureResponse]
  describe 'upsert_feature test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
