=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for LeanixApi::ModelsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ModelsApi' do
  before do
    # run before each test
    @api_instance = LeanixApi::ModelsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ModelsApi' do
    it 'should create an instance of ModelsApi' do
      expect(@api_instance).to be_instance_of(LeanixApi::ModelsApi)
    end
  end

  # unit tests for create_access_control_entity
  # createAccessControlEntity
  # Creates an access control entity
  # @param [Hash] opts the optional parameters
  # @option opts [AccessControlEntity] :body New access control entity
  # @return [AccessControlEntityResponse]
  describe 'create_access_control_entity test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_access_control_entity
  # deleteAccessControlEntity
  # Deletes an access control entity
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_access_control_entity test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_access_control_entities
  # getAccessControlEntities
  # Retrieves all access control entities
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size Number of reports to be returned, maximum is 100
  # @option opts [String] :cursor Marks the position of the first element that should be returned
  # @option opts [String] :sorting The field to sort the results by
  # @option opts [String] :sort_direction The direction of the sorting
  # @return [AccessControlEntityListResponse]
  describe 'get_access_control_entities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_action_batch
  # getMetaModelActionBatch
  # Return a single action batch
  # @param id Id of the requested actionBatch
  # @param [Hash] opts the optional parameters
  # @return [MetaModelActionBatchResponse]
  describe 'get_action_batch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_action_batches
  # getMetaModelActionBatches
  # Return existing action batches
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page number to access (1 indexed, defaults to 1)
  # @option opts [Integer] :size The page size requested (defaults to 20, max 100)
  # @return [MetaModelActionBatchListResponse]
  describe 'get_action_batches test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_authorization
  # getAuthorization
  # Provides all authorization roles were for each role a set of permission is defined.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id 
  # @return [AuthorizationRolesResponse]
  describe 'get_authorization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_data_model
  # getDataModel
  # Retrieves the model for a workspace
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id 
  # @return [DataModelDefinitionResponse]
  describe 'get_data_model test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_enriched_data_model
  # getEnrichedDataModel
  # Retrieves the model for a workspace, including redundant data that makes life easy for the web front end
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id 
  # @return [DataModelDefinitionResponse]
  describe 'get_enriched_data_model test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_fact_sheet_resource_model
  # getFactSheetResourceModel
  # Retrieves the fact sheet resource model for a workspace
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id 
  # @return [FactSheetResourceModelResponse]
  describe 'get_fact_sheet_resource_model test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_language
  # getLanguage
  # Get the given language
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id 
  # @return [LanguageResponse]
  describe 'get_language test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_meta_model
  # getMetaModel
  # DEPRECATED: This endpoint provides an aggregated version of some of the other models available under /models. The MetaModel is only intended for internal use and will soon be removed from the public OpenAPI spec.
  # @param [Hash] opts the optional parameters
  # @return [MetaModelResponse]
  describe 'get_meta_model test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_meta_model_for_type
  # getMetaModelForFactSheetType
  # DEPRECATED: This endpoint provides an aggregated version of some of the other models available under /models. The MetaModel is only intended for internal use and will soon be removed from the public OpenAPI spec.
  # @param fact_sheet_type 
  # @param [Hash] opts the optional parameters
  # @return [MetaModelResponse]
  describe 'get_meta_model_for_type test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_preview_of_affected_data
  # getPreviewOfAffectedData
  # Provides a preview for affected data that will be deleted if corresponding FactSheet Type will be deleted.
  # @param fact_sheet_type 
  # @param [Hash] opts the optional parameters
  # @return [FSTypeDeletionPreviewResponse]
  describe 'get_preview_of_affected_data test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_reporting_model
  # getReportingModel
  # Retrieves the report model for a workspace
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id 
  # @return [ReportingModelResponse]
  describe 'get_reporting_model test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_view_model
  # getViewModel
  # Retrieves the view model for a workspace
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id 
  # @return [ViewModelResponse]
  describe 'get_view_model test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_action_batches
  # postMetaModelActionBatches
  # DEPRECATED: This endpoint provides an aggregated version of some of the other models available under /models. The MetaModel is only intended for internal use and will soon be removed from the public OpenAPI spec.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<ActionBatchItem>] :body List of actions to be processed
  # @return [MetaModelActionBatchResponse]
  describe 'post_action_batches test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for read_access_control_entity
  # getAccessControlEntity
  # Reads an access control entity
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [AccessControlEntityResponse]
  describe 'read_access_control_entity test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_access_control_entity
  # updateAccessControlEntity
  # Updates an access control entity
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [AccessControlEntity] :access_control_entity 
  # @return [AccessControlEntityResponse]
  describe 'update_access_control_entity test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_authorization
  # updateAuthorization
  # Updates all authorization roles for a given workspace. This means all existing roles and its permissions will be overriden
  # @param body The authorization configuration for the workspace which contains all roles and its permissions
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id 
  # @return [Response]
  describe 'update_authorization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_data_model
  # updateDataModel
  # Updates the data model for a workspace
  # @param body the data model for the workspace
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :force whether changes should be forced
  # @option opts [String] :workspace_id 
  # @return [DataModelUpdateResponse]
  describe 'update_data_model test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_fact_sheet_resource_model
  # updateFactSheetResourceModel
  # Updates the fact sheet resource model for a workspace
  # @param body the fact sheet resource model for the workspace
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id 
  # @return [nil]
  describe 'update_fact_sheet_resource_model test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_language
  # updateLanguage
  # Updates the given language
  # @param id 
  # @param definition 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id 
  # @return [Response]
  describe 'update_language test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_reporting_model
  # updateReportingModel
  # Updates the report model for a workspace
  # @param body the report model for the workspace
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id 
  # @return [nil]
  describe 'update_reporting_model test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_view_model
  # updateViewModel
  # Updates the view model for a workspace
  # @param body the view model for the workspace
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id 
  # @return [nil]
  describe 'update_view_model test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
