=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for LeanixApi::SettingsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SettingsApi' do
  before do
    # run before each test
    @api_instance = LeanixApi::SettingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsApi' do
    it 'should create an instance of SettingsApi' do
      expect(@api_instance).to be_instance_of(LeanixApi::SettingsApi)
    end
  end

  # unit tests for get_model_customization
  # getFactSheetSettings
  # @param fact_sheet_type 
  # @param [Hash] opts the optional parameters
  # @return [FactSheetSettingsResponse]
  describe 'get_model_customization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_settings
  # getSettings
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id The workspace id to fetch settings for.
  # @return [SettingsResponse]
  describe 'get_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_models_with_customization
  # putFactSheetSettings
  # @param fact_sheet_type 
  # @param body customization
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_models_with_customization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_settings
  # updateSettings
  # @param body the settings for the workspace
  # @param [Hash] opts the optional parameters
  # @return [Response]
  describe 'update_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
