=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixApi::ApprovalWorkflowConfiguration
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixApi::ApprovalWorkflowConfiguration do
  let(:instance) { LeanixApi::ApprovalWorkflowConfiguration.new }

  describe 'test an instance of ApprovalWorkflowConfiguration' do
    it 'should create an instance of ApprovalWorkflowConfiguration' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixApi::ApprovalWorkflowConfiguration)
    end
  end

  describe 'test attribute "enabled"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "approval_strategy"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["MANUAL", "AUTOMATIC"])
      # validator.allowable_values.each do |value|
      #   expect { instance.approval_strategy = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "rejected_state"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "mandatory_subscription_types"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["ACCOUNTABLE", "RESPONSIBLE", "OBSERVER"])
      # validator.allowable_values.each do |value|
      #   expect { instance.mandatory_subscription_types = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "mandatory_base_fields"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
