=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixApi::Deletion
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixApi::Deletion do
  let(:instance) { LeanixApi::Deletion.new }

  describe 'test an instance of Deletion' do
    it 'should create an instance of Deletion' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixApi::Deletion)
    end
  end

  describe 'test attribute "deletion_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["FACT_SHEET", "RELATION", "FACT_SHEET_FIELD", "FACT_SHEET_FIELD_VALUE", "RELATION_FIELD", "RELATION_FIELD_VALUE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.deletion_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "info1"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "info2"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
