=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixApi::LxField
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixApi::LxField do
  let(:instance) { LeanixApi::LxField.new }

  describe 'test an instance of LxField' do
    it 'should create an instance of LxField' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixApi::LxField)
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["StringValue", "IntegerValue", "DoubleValue", "DateValue", "SingleSelect", "Classification", "Location", "Lifecycle", "ExternalId", "MultipleSelect", "ProjectStatusProgress"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

end
