=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixApi::MostRecentAction
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixApi::MostRecentAction do
  let(:instance) { LeanixApi::MostRecentAction.new }

  describe 'test an instance of MostRecentAction' do
    it 'should create an instance of MostRecentAction' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixApi::MostRecentAction)
    end
  end

  describe 'test attribute "action_date_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "action_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["CREATED", "VIEWED", "UPDATED", "SHARED"])
      # validator.allowable_values.each do |value|
      #   expect { instance.action_name = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "shared_by_user_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "my_views"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
