=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixApi::PermissionsField
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixApi::PermissionsField do
  let(:instance) { LeanixApi::PermissionsField.new }

  describe 'test an instance of PermissionsField' do
    it 'should create an instance of PermissionsField' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixApi::PermissionsField)
    end
  end

  describe 'test attribute "_self"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["READ", "UPDATE", "CREATE", "DELETE", "ARCHIVE", "IMPORT", "EXPORT", "INLINE_EDIT", "UNLOCK", "CHANGE_OWNER", "MANAGE_PREDEFINED", "MANAGE_CONTENT", "ADMINISTRATE", "DESIGN_SURVEY", "COLLECT_RESPONSES", "ANALYZE_RESULTS"])
      # validator.allowable_values.each do |value|
      #   expect { instance._self = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "create"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "read"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "update"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "delete"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
