=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixApi::RegexValidator
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixApi::RegexValidator do
  let(:instance) { LeanixApi::RegexValidator.new }

  describe 'test an instance of RegexValidator' do
    it 'should create an instance of RegexValidator' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixApi::RegexValidator)
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
