=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixApi::RelationGroupedBy
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixApi::RelationGroupedBy do
  let(:instance) { LeanixApi::RelationGroupedBy.new }

  describe 'test an instance of RelationGroupedBy' do
    it 'should create an instance of RelationGroupedBy' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixApi::RelationGroupedBy)
    end
  end

  describe 'test attribute "fact_sheet_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "enabling_relation"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "grouping_relation"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
