=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixApi::ReportLxStateConfiguration
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixApi::ReportLxStateConfiguration do
  let(:instance) { LeanixApi::ReportLxStateConfiguration.new }

  describe 'test an instance of ReportLxStateConfiguration' do
    it 'should create an instance of ReportLxStateConfiguration' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixApi::ReportLxStateConfiguration)
    end
  end

  describe 'test attribute "for_fact_sheet_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "keys"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["BROKEN_QUALITY_SEAL", "DRAFT", "REJECTED", "APPROVED"])
      # validator.allowable_values.each do |value|
      #   expect { instance.keys = value }.not_to raise_error
      # end
    end
  end

end
