=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixApi::SectionCompletion
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixApi::SectionCompletion do
  let(:instance) { LeanixApi::SectionCompletion.new }

  describe 'test an instance of SectionCompletion' do
    it 'should create an instance of SectionCompletion' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixApi::SectionCompletion)
    end
  end

end
