=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixApi::SignavioGlossaryCategoryMapping
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixApi::SignavioGlossaryCategoryMapping do
  let(:instance) { LeanixApi::SignavioGlossaryCategoryMapping.new }

  describe 'test an instance of SignavioGlossaryCategoryMapping' do
    it 'should create an instance of SignavioGlossaryCategoryMapping' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixApi::SignavioGlossaryCategoryMapping)
    end
  end

  describe 'test attribute "active"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "strict"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "glossary_category_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "leanix_relation_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "master"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["LEANIX", "SIGNAVIO"])
      # validator.allowable_values.each do |value|
      #   expect { instance.master = value }.not_to raise_error
      # end
    end
  end

end
