=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixApi::SubscriptionSettings
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixApi::SubscriptionSettings do
  let(:instance) { LeanixApi::SubscriptionSettings.new }

  describe 'test an instance of SubscriptionSettings' do
    it 'should create an instance of SubscriptionSettings' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixApi::SubscriptionSettings)
    end
  end

  describe 'test attribute "subscription_types"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["ACCOUNTABLE", "RESPONSIBLE", "OBSERVER"])
      # validator.allowable_values.each do |value|
      #   expect { instance.subscription_types = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "role_assignment"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["SINGLE", "MULTIPLE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.role_assignment = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "role_mode"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ON_THE_FLY", "OPTIONAL", "REQUIRED"])
      # validator.allowable_values.each do |value|
      #   expect { instance.role_mode = value }.not_to raise_error
      # end
    end
  end

end
