=begin
#Pathfinder

#Core application for storage and analysis of IT landscape data

The version of the OpenAPI document: 5.0.1100

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for LeanixApi::TagSettings
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe LeanixApi::TagSettings do
  let(:instance) { LeanixApi::TagSettings.new }

  describe 'test an instance of TagSettings' do
    it 'should create an instance of TagSettings' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(LeanixApi::TagSettings)
    end
  end

  describe 'test attribute "tagging_mode"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ON_THE_FLY", "PRE_DEFINED_ONLY", "PRE_DEFINED_OR_ON_THE_FLY"])
      # validator.allowable_values.each do |value|
      #   expect { instance.tagging_mode = value }.not_to raise_error
      # end
    end
  end

end
